import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import type { Article, LabEntry, Product } from "@/lib/content";
import { formatDate, readingTime } from "@/lib/content";

export function StatusBadge({ status }: { status: Product["status"] | LabEntry["status"] }) { return <span className={`status-badge status-${status.toLowerCase().replaceAll(" ", "-")}`}><i aria-hidden="true" />{status}</span>; }
export function ProductCard({ product }: { product: Product }) { const href = product.slug === "electricaldyev" ? "/products/electricaldyev/" : "/lab/"; return <article className={`product-card ${product.slug === "electricaldyev" ? "product-card-electrical" : ""}`}><div className="product-card-top"><StatusBadge status={product.status} /><span>{product.category}</span></div>{product.slug === "electricaldyev" ? <div className="product-preview" aria-label="ElectricalDyev product interface preview"><strong>ElectricalDyev</strong><div><span>Power</span><span>Cable</span><span>Voltage drop</span></div><p>Transparent inputs · visible working · browser-local project</p></div> : <div className="abstract-panel"><span>{product.slug === "boq-workspace" ? "01 / scope → quantity → estimate" : "Ideas in progress"}</span></div>}<h2>{product.name}</h2><p>{product.summary}</p><Link href={href} className="text-link">{product.slug === "electricaldyev" ? "Explore product" : "View in the Lab"}<ArrowRight aria-hidden="true" /></Link></article>; }
export function ArticleCard({ article, compact = false }: { article: Article; compact?: boolean }) { return <article className={`article-card ${compact ? "article-card-compact" : ""}`}><Link href={`/articles/${article.slug}/`} className="article-image"><Image src={article.image} alt={article.imageAlt} fill sizes="(max-width: 700px) 100vw, 33vw" /></Link><div className="article-card-body"><p className="article-meta">{article.category} <span>·</span> {readingTime(article)} min read</p><h2><Link href={`/articles/${article.slug}/`}>{article.title}</Link></h2><p>{article.description}</p><div className="article-card-footer"><time dateTime={article.publishedAt}>{formatDate(article.publishedAt)}</time><Link href={`/articles/${article.slug}/`} aria-label={`Read ${article.title}`}><ArrowRight aria-hidden="true" /></Link></div></div></article>; }
export function LabCard({ entry }: { entry: LabEntry }) { return <article className="lab-card"><div className="lab-visual"><span className="lab-code">{entry.code}</span><div className="lab-lines" aria-hidden="true"><i /><i /><i /></div></div><StatusBadge status={entry.status} /><h2>{entry.title}</h2><p>{entry.description}</p><span className="lab-detail">{entry.detail}</span><Link className="text-link" href="/lab/">{entry.status === "Question" ? "Read note" : "View study"}<ArrowRight aria-hidden="true" /></Link></article>; }
export function ExternalProductLink({ className = "button button-product", children = "Open ElectricalDyev" }: { className?: string; children?: React.ReactNode }) { return <a className={className} href="https://electrical.dyev.in/" target="_blank" rel="noreferrer">{children}<ArrowUpRight aria-hidden="true" /></a>; }
