import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArticleCard, ExternalProductLink } from "@/components/content-cards";
import { articles, formatDate, getArticle, readingTime } from "@/lib/content";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const article = getArticle((await params).slug); if (!article) return {}; return { title: article.title, description: article.description, alternates: { canonical: `/articles/${article.slug}/` }, openGraph: { type: "article", title: article.title, description: article.description, publishedTime: article.publishedAt, images: [{ url: article.image, alt: article.imageAlt }] }, twitter: { card: "summary_large_image", title: article.title, description: article.description, images: [article.image] } }; }
export default async function ArticlePage({ params }: Props) { const article = getArticle((await params).slug); if (!article) notFound(); const related = articles.filter((candidate) => candidate.slug !== article.slug).slice(0,2); const headings = article.blocks.filter((block) => block.type === "heading"); const articleUrl = `https://dyev.in/articles/${article.slug}/`; const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Article", headline: article.title, description: article.description, datePublished: article.publishedAt, author: { "@type": "Organization", name: "Dyev" }, publisher: { "@type": "Organization", name: "Dyev", url: "https://dyev.in" }, mainEntityOfPage: articleUrl }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Dyev", item: "https://dyev.in/" }, { "@type": "ListItem", position: 2, name: "Articles", item: "https://dyev.in/articles/" }, { "@type": "ListItem", position: 3, name: article.title, item: articleUrl }] }] }; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="article-layout shell"><aside className="article-side"><h2>Contents</h2><nav>{headings.map((heading, index) => <a key={heading.text} href={`#section-${index + 1}`}>{String(index + 1).padStart(2,"0")}. {heading.text}</a>)}</nav></aside><article><header className="article-header"><div className="breadcrumbs"><Link href="/articles/">← Articles</Link></div><p className="article-meta">{article.category} · {formatDate(article.publishedAt)} · {readingTime(article)} min read</p><h1>{article.title}</h1><p className="article-deck">{article.description}</p><p className="article-byline"><i aria-hidden="true" />By Dyev</p></header><div className="article-hero-image"><Image src={article.image} alt={article.imageAlt} fill priority sizes="(max-width: 900px) 100vw, 760px" /></div><div className="article-body">{article.blocks.map((block, index) => block.type === "heading" ? <h2 id={`section-${headings.indexOf(block) + 1}`} key={`${block.type}-${index}`}>{block.text}</h2> : block.type === "quote" ? <blockquote key={`${block.type}-${index}`}>{block.text}</blockquote> : block.type === "callout" ? <aside className="article-callout" key={`${block.type}-${index}`}>{block.text}</aside> : <p key={`${block.type}-${index}`}>{block.text}</p>)}</div>{article.relatedProduct && <aside className="article-product-cta"><div><p className="eyebrow">A Dyev product</p><h2>Explore ElectricalDyev</h2><p>Transparent preliminary electrical calculation tools, with visible assumptions and browser-private project data.</p></div><ExternalProductLink className="button button-product">Open tool</ExternalProductLink></aside>}<section className="article-related"><p className="eyebrow">Related articles</p><div className="article-grid">{related.map((item) => <ArticleCard key={item.slug} article={item} />)}</div></section></article></div></>; }
